### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by perguth** [Laverna/static-laverna#2]
I find it a quite good idea to have a Github hosted version of Laverna! Any chance this will be up again soon?

**Comment by perguth** [comment]
Happily using it.

**Comment by tvvocold** [comment]
Github hosted? but how?
I had create a org && fork this repo && rename it to org.github.io && set  Default branch to gh-page,but got 404 error.
https://github.com/notehere/notehere.github.io

**Comment by perguth** [comment]
@tvvocold https://help.github.com/categories/github-pages-basics/

**Comment by tvvocold** [comment]
@pguth 
Can you be more  specific plz? It seems [yours](http://pguth.github.io/static-laverna) is 404 too, but on [rodoviario'](https://github.com/Laverna/static-laverna/issues/4#issuecomment-111190737) is working.

**Comment by perguth** [comment]
@tvvocold Ah, I never exactly tried. I use the one hosted here currently. But you need to read up on the doku (GH-Pages) first. Seems you're doing it wrong here: "`&& set Default branch to gh-page`"
