### ISSUE TITLE
Didn't work on github pages.

### ISSUE THREAD

**Issue by tvvocold** [Laverna/static-laverna#4]
See https://github.com/Laverna/static-laverna/issues/2#issuecomment-111183679

**Comment by tvvocold** [comment]
I found that https://github.com/rodoviario/static-laverna is working on http://rodoviario.github.io/static-laverna but [the others](https://github.com/Laverna/static-laverna/network/members) didn't work.Maybe it's a [Jekyll ](https://github.com/rodoviario/rodoviario.github.io) problem or coz [this commit](https://github.com/rodoviario/static-laverna/commit/a184088d19973ef1b13a7d689cc12da7463c98de)?
:)

**Comment by tvvocold** [comment]
@rodoviario 
Could you give some help ?Thx!

**Comment by tvvocold** [comment]
@wwebfor

**Comment by tvvocold** [comment]
@pguth
Finally, i figure it out:)
1st u need fork this repo, and set default branch to master, then just edit something (like add a newline) in gh-pages branch of your fork.After this trigger, hit the http://yourname.github.io/static-laverna ,Done!

And you can rename it to whatever you like,see https://github.com/tvvocold/note

**Comment by wwebfor** [comment]
I think it is not necessary to change the default branch to master. I just tried to trigger some change in gh-pages branch and it worked.

Thanks for sharing the solution to the problem.

**Comment by perguth** [comment]
In general: If the `gh-pages` website does not seem to update, one needs to trigger a rebuild by pushing to the repo the Github support told me.
