### ISSUE TITLE
How to set the default language?

### ISSUE THREAD

**Issue by tvvocold** [Laverna/static-laverna#5]
I try to set [L22 of manifest.webapp](https://github.com/Laverna/static-laverna/blob/b6a6c753690e2f48298e75c058112680b78533d9/manifest.webapp#L22) to zh_cn and add the  translation.json in /locales/zh_cn/, but it seems didn't work.

**Comment by tvvocold** [comment]
@wwebfor @wwwredfish

**Comment by wwebfor** [comment]
In order to set the default language, you need to open this file https://github.com/Laverna/laverna/blob/master/app/scripts/helpers/i18next.js#L29. But why do you need to set the default language when you can change language in the settings page?

**Comment by tvvocold** [comment]
@wwebfor 

> But why do you need to set the default language when you can change language in the settings page?

Because the default setting page is lack of Chinese.(zh_cn) (Check it in https://laverna.cc/index.html#/settings or http://laverna.github.io/static-laverna/#/settings)

> In order to set the default language, you need to open this file https://github.com/Laverna/laverna/blob/master/app/scripts/helpers/i18next.js#L29.

The i18next.js is Not exit  in https://github.com/Laverna/static-laverna :)

**Comment by wwebfor** [comment]
You're right. For now, you can switch to another language by opening Developer console and executing:

```
localStorage.setItem('vimarkable.configs-appLang', JSON.stringify({name: 'appLang', value: 'zh_cn'}));
```

**Comment by tvvocold** [comment]
> localStorage.setItem('vimarkable.configs-appLang', JSON.stringify({name: 'appLang', value: 'zh_cn'}));
> <undefined

That's what i got in chrome console.
BTW, is there any way to change the lang with js?

**Comment by wwebfor** [comment]
It didn't take effect because right now zh_cn locale doesn't exist in the static version https://github.com/Laverna/static-laverna/tree/gh-pages/locales

**Comment by asalthobaity** [comment]
Please commit the ar locale into the static version.

**Comment by wwebfor** [comment]
The locales were updated.
